language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
before_script:
  - psql -c 'create database dbkaya_test;' -U postgres
services:
  - postgresql
before_install:
  - cd server-side 
script:
  - npm test

