language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - cd server-side 
install:
  - npm install
  # - npm install -g db-migrate
  # - npm install db-migrate-pg
before_script:
  - psql -c 'create database dbkaya_test;' -U postgres
  - psql -c "CREATE USER admin01 WITH PASSWORD 'root';" -U postgres
  # - cd src/infra/sequelize db:migrate
  # - db-migrate up:all
script:
  - npm test

