language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - npm install -g npm --cache-min 999999999
install:
  - npm install
  - npm install -g sequelize-cli
  # - npm install -g codecov
before_script:
  - psql -c 'create database dbkaya_test;' -U postgres
  - psql -c "CREATE USER admin01 WITH PASSWORD 'root';" -U postgres
  - cd src/infra/sequelize
  - sequelize db:migrate
script:
  - npm test

