language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - cd server-side 
install:
  - npm install
before_script:
  # - psql -c 'create database dbkaya_test;' -U postgres
  - cd src/infra/sequelize sequelize db:migrate
  # - npm start
script:
  - npm test

