language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database dbkaya_test;' -U postgres
  - node_modules/.bin/sequelize db:migrate
  - node_modules/.bin/sequelize db:seed:all
before_install:
  - cd server-side 
install:
  - npm install
script:
  - npm test
services:
  - postgresql
